#!/bin/sh

if [ $# -ne 3 ]; then 
     echo "Cannot start. Pass user, password and id to follow as args 1-3." > \
	 /var/log/cybercritic.log
     exit 1
fi

detachtty --dribble-file /var/log/cybercritic-dribble \
	  --log-file /var/log/cybercritic.log \
	  --pid-file /var/run/cybercritic.pid \
  	  /var/run/cybercritic-socket \
    ./cybercritic $1 $2 $3
